### ISSUE TITLE
Remove browser autocomplete

### ISSUE THREAD

**Issue by srocerer** [frikinside/vue3-simple-typeahead#1]
<img width="347" alt="Screenshot 2021-10-14 at 09 19 41" src="https://user-images.githubusercontent.com/4624216/137262717-c418fda2-fc71-4679-9ee3-f50335006a52.png">

Adding `autocomplete="off"` on input should solve the problem.

**Comment by frikinside** [comment]
Done!
Released a new subversion [v1.0.2](https://github.com/frikinside/vue3-simple-typeahead/releases/tag/v1.0.2) without the browser autocomplete.
Good call, I didn't realize that issue (i usually had the autocomplete disabled in browsers).
