### ISSUE TITLE
If create vue3-simple-typeahead into modal, close 

### ISSUE THREAD

**Issue by tecprac** [frikinside/vue3-simple-typeahead#10]
When I insert the component inside a modal when selecting an element with [mouseenter] it closes the modal, with the [TAB] or [ENTER] key it does not happen. Can you help me, please

**Comment by frikinside** [comment]
Sorry for the late, late, late response, I've been really busy and didn't pay attention to this.

Are you still facing this issue?
Is a custom modal or are you using a library?

**Comment by montalvoalmag** [comment]
Don't worry, the problem was in my modal. Thanks for your attention.
I hope you are calmer

**Comment by frikinside** [comment]
Glad to hear that you solve the problem!
