### ISSUE TITLE
Error in example @ README.md

### ISSUE THREAD

**Issue by evo42** [frikinside/vue3-simple-typeahead#14]
Hi!

Tried your component with Inertia and got errors with the example code - later on noticed it's because the example is not correct - please remove the dots (`,...`) so others have a better experience `:items="['One','Two','Three',...]"`

https://github.com/evo42/vue3-simple-typeahead/pull/1/commits/9a8217ca884aab45312982fde929984adec18a6e

**Comment by frikinside** [comment]
You are right, the sample should be a working one, and is unnecesary to represent in the example that the list could be bigger.

Updated!
