### ISSUE TITLE
Add ability to add content above the list

### ISSUE THREAD

**Issue by rocevas** [frikinside/vue3-simple-typeahead#3]
It would be nice to have the ability to add a button above the list.

Example:
<img width="231" alt="Screenshot 2021-10-14 at 22 12 19" src="https://user-images.githubusercontent.com/39726634/137381131-87aeb1da-c14f-473f-b37c-f5cf42dcd52d.png">

**Comment by frikinside** [comment]
I take a look into this.
Maybe I could add a slot to the top and bottom of the list.

**Comment by frikinside** [comment]
Added slots to allow this.
### Slots

| Slot                                 | Parent                                  | Props                                     | Description                                                     |
| :----------------------------------- | :-------------------------------------- | :---------------------------------------- | :-------------------------------------------------------------- |
| [`#list-header`](#list-header)       | `div.simple-typeahead-list-header`      |                                           | Slot to be show at top of the suggestion list                   |
| [`#list-item-text`](#list-item-text) | `span.simple-typeahead-list-item-text'` |                                           | Slot to customize the text of every item in the suggestion list |
| [`#list-footer`](#list-footer)       | `div.simple-typeahead-list-footer`      | `item`, `itemProjection`, `boldMatchText` | Slot to be show at bottom of the suggestion list                |

Please check the readme to see more info and a simple example.
