### ISSUE TITLE
Ability project two variables

### ISSUE THREAD

**Issue by srocevas** [frikinside/vue3-simple-typeahead#5]
For example to show product and its price. 
Problem: `:itemProjection="(item) => {return item.name + ' ' + item.price }"` <- can't use custom CSS on price.

Possible solution?
```
<span v-html="slot.boldMatchText(slot.itemProjection(slot.item.name))"></span>
<span class="text-gray-500 ml-4" v-html="slot.boldMatchText(slot.itemProjection(slot.item.price))"></span>
```

**Comment by frikinside** [comment]
With the slots that problem shouldn't exist.
You can just make everything you want inside the item slot without using the `itemProjection` (or using only for one of the properties).
By default, the itemProjection is used for the search and for display, you could still use the itemProjection for search and use the slot to customize the display.

Using the item projection for search the same way like in your example:
`:itemProjection="(item) => {return item.name + ' ' + item.price }"`

And the slot template looks like this:
```html
<template #list-item-text="slot">
    <span v-html="slot.boldMatchText(slot.item.name)"></span>
    <span class="text-gray-500 ml-4" v-html="slot.boldMatchText(slot.item.price)"></span>
</template>
```

I hope I've been able to explain myself correctly.
