### ISSUE TITLE
Ability to clear input

### ISSUE THREAD

**Issue by Sell24** [frikinside/vue3-simple-typeahead#6]
Would it possible to create a function to clear the input?

I realize I can clear the input using a reference to the variable (which I am doing now) but something less coupled would be nice.

**Comment by frikinside** [comment]
I don't think it's possible to expose a method from a child component to be called from a parent component.
I've been trying to look for a way to do it or a workaround but nothing seem to function properly.
I think the only way to do it is using `ref` like you already did.

Well, to be honest, there is another way. Not by exposing a function to be used on parent component, but with the use of `v-model`. I've been working a bit on a `v-model` alternative for the plugin, but I encountered a few problems which I couldn't solve. Yet.
But feel free to suggest a solution or make a PR if you want. I'll let you know if I finish the `v-model` version if you want.

P.D. Sorry for the late response. I've been on vacation and a bit disconected for a few weeks.

**Comment by frikinside** [comment]
I update the [v-model branch](https://github.com/frikinside/vue3-simple-typeahead/tree/v-model) with a usable component. The testing is not finish but looks promising. You could try to play around with this version (at the `/dist` folder).

**Comment by andydeforest** [comment]
I was able to clear input by assigning the typeahead a ref and using this: `this.$refs.typeahead.input = '';`

**Comment by x4m3** [comment]
I was able to clear input like this:

in my js code:
```typescript
// Import component
import SimpleTypeahead from "vue3-simple-typeahead";

// Declare ref
const refSimpleTypeahead = ref(null);

// Use where needed
refSimpleTypeahead.value?.clearInput();
```

in my template:
```vue
<SimpleTypeahead ref="refSimpleTypeahead"></SimpleTypeahead>
```
