### ISSUE TITLE
How to send input text to a method, which returns the results into the array to be displayed

### ISSUE THREAD

**Issue by droidzone** [frikinside/vue3-simple-typeahead#9]
My situation is that when the user types in more than 4 characters in the input field, the text needs to be sent to a server by axios, and the resulting list/array has to be shown as the selection list. Currently I'm doing a very roundabout way without any library.

**Comment by frikinside** [comment]
This component doesn't support a lazy/ajax list, but you can make it work with a few custom implementations in your code.
Using the onInput event to fetch the list and bind it to the component. Something like this:

```html
<template>
    <vue3-simple-typeahead:items="list" @onInput="onInput" :minInputLength="4" />
</template>
```

```js
<script>
import Vue3SimpleTypeahead from '@/vue3-simple-typeahead.vue';
export default {
    components: {
        Vue3SimpleTypeahead,
    },
    data(){
        list: []
    },
    methods: {
        onInput(event) {
            if (event.input.length > 3) {
                axios
                  .get(`https://api.get/list/${event.input}`)
                  .then(response => (this.list= response));
            } else {
                this.list= [];
            }
        }
    }
};
</script>
```

I know is not the desired way, but it should work. Let me know if this helps or you need further assintance.
